version: "3.8"

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_db  # Base de datos unificada
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      MYSQL_BIND_ADDRESS: 0.0.0.0
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_wallet:/var/lib/mysql  # Volumen persistente para MySQL
    networks:
      - mynetwork

  # Keycloak Service
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    environment:
      - KEYCLOAK_ADMIN=admin  # Admin user for Keycloak
      - KEYCLOAK_ADMIN_PASSWORD=admin  # Admin password for Keycloak
      - KEYCLOAK_HTTP_PORT=8080  # Expose Keycloak on port 8080
    ports:
      - "8088:8080"  # Access Keycloak on http://localhost:8088
    networks:
      - mynetwork
    depends_on:
      - mysql-db  # Wait for MySQL to be ready

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data_wallet:
    driver: local  # Definir el driver del volumen
